### ISSUE TITLE
insert failing on Postgres 9.5.3

### ISSUE THREAD

**Issue by natefinch** [xo/xo#126] opened 2017-07-21 16:39 UTC
The generated code for insert looks something like this:

```
const sqlstr = `INSERT INTO public.users (` +
		`id, email, first_name, last_name` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`

	// run query
	XOLog(sqlstr, u.ID, u.Email, u.FirstName, u.LastName)
	err = db.QueryRow(sqlstr, u.ID, u.Email, u.FirstName, u.LastName).Scan(&u.ID)
	if err != nil {
		return err
	}
```
However, the scan always fails with no rows returned, because there's no `RETURNING id` in the SQL, so there's nothing returned.

**Comment by natefinch** [comment] 2017-07-21 17:25
Looking at the template it looks like it's seomthing to do with manual PK vs automatic. I'm not sure I understand what the difference is.  This is the definition of the ID column in my DB:

` id                               | uuid                     | not null default uuid_generate_v4()`

**Comment by natefinch** [comment] 2017-07-21 19:16
So my guess is that the not null + default is screwing up the generator.  The "not null" part tells it to use a normal uuid, not a NullUUID, but that forces me to generate the ID on insert... but if I pass in the ID then postgres doesn't generate one and thus doesn't return anything, so the scan fails with no rows.

**Comment by natefinch** [comment] 2017-07-21 19:25
Hmm. so interesting, there's no separate path for nullable UUIDs here:
https://github.com/knq/xo/blob/master/loaders/postgres.go#L185
So there's currently no way to pass a null UUID into the DB and let it generate the value.  That seems like something that should be fixed?

**Comment by turnkey-commerce** [comment] 2017-07-21 22:24
Thanks Nate for reporting this, I will take a look.  To answer your earlier question the idea on the "manual pk" is to handle cases when the PK is not being auto-created, for example when it is on a child table as in a many-to-many.  This looks like a case that is mixed and agree it should be fixed.

**Comment by natefinch** [comment] 2017-07-21 22:51
Along similar lines I have a fix to make uuids nullable, as well as account
for fields that are not null but have default values that can be set, so
like in this case I can leave out the id let the DB generate it, even if
the column can't be null.

I'll submit an initial PR so you can take a look.

I'm working on putting this into production at Mattel, so I may have a few
PRs for you as I hit snags.

**Comment by mendio** [comment] 2019-08-05 15:32
Hey, any news on that ?  I think I'm having the same issue. (pgsql)
`Insert()` returns `sql: no rows in result set` when inserting a duplicated entity, instead of `pq: duplicate key value violates unique constraint xyz`.
Adding `RETURNING uuid` at the end of the insert statement fixes the issue.

Is this an expected behaviour or am I misusing the lib ? 


```
CREATE TABLE pages(
  uuid                VARCHAR(255)    NOT NULL      PRIMARY KEY,
  ...
)
```
`models/page.xo.go`
```
type Page struct {
	UUID            string         `json:"uuid"`              // uuid
        ...
}

```
The code generated seems to be what the template describes.

```
	const sqlstr = `INSERT INTO pages (` +
		`uuid, ...` +
		`) VALUES (` +
		`$1, ...` +
		`)`

	// run query
	XOLog(sqlstr, p.UUID, ...)
	err = db.QueryRow(sqlstr, p.UUID, ...).Scan(&p.UUID)
	if err != nil {
		return err
	}

```

**Closed** 2021-06-08 09:24 UTC
